// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Transcription is the predicate function for transcription builders.
type Transcription func(*sql.Selector)

// Translation is the predicate function for translation builders.
type Translation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
