// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/pluja/anysub/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/pluja/anysub/ent/transcription"
	"github.com/pluja/anysub/ent/translation"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Transcription is the client for interacting with the Transcription builders.
	Transcription *TranscriptionClient
	// Translation is the client for interacting with the Translation builders.
	Translation *TranslationClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Transcription = NewTranscriptionClient(c.config)
	c.Translation = NewTranslationClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Transcription: NewTranscriptionClient(cfg),
		Translation:   NewTranslationClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Transcription: NewTranscriptionClient(cfg),
		Translation:   NewTranslationClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Transcription.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Transcription.Use(hooks...)
	c.Translation.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Transcription.Intercept(interceptors...)
	c.Translation.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *TranscriptionMutation:
		return c.Transcription.mutate(ctx, m)
	case *TranslationMutation:
		return c.Translation.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// TranscriptionClient is a client for the Transcription schema.
type TranscriptionClient struct {
	config
}

// NewTranscriptionClient returns a client for the Transcription from the given config.
func NewTranscriptionClient(c config) *TranscriptionClient {
	return &TranscriptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `transcription.Hooks(f(g(h())))`.
func (c *TranscriptionClient) Use(hooks ...Hook) {
	c.hooks.Transcription = append(c.hooks.Transcription, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `transcription.Intercept(f(g(h())))`.
func (c *TranscriptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Transcription = append(c.inters.Transcription, interceptors...)
}

// Create returns a builder for creating a Transcription entity.
func (c *TranscriptionClient) Create() *TranscriptionCreate {
	mutation := newTranscriptionMutation(c.config, OpCreate)
	return &TranscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Transcription entities.
func (c *TranscriptionClient) CreateBulk(builders ...*TranscriptionCreate) *TranscriptionCreateBulk {
	return &TranscriptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TranscriptionClient) MapCreateBulk(slice any, setFunc func(*TranscriptionCreate, int)) *TranscriptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TranscriptionCreateBulk{err: fmt.Errorf("calling to TranscriptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TranscriptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TranscriptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Transcription.
func (c *TranscriptionClient) Update() *TranscriptionUpdate {
	mutation := newTranscriptionMutation(c.config, OpUpdate)
	return &TranscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TranscriptionClient) UpdateOne(t *Transcription) *TranscriptionUpdateOne {
	mutation := newTranscriptionMutation(c.config, OpUpdateOne, withTranscription(t))
	return &TranscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TranscriptionClient) UpdateOneID(id int) *TranscriptionUpdateOne {
	mutation := newTranscriptionMutation(c.config, OpUpdateOne, withTranscriptionID(id))
	return &TranscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Transcription.
func (c *TranscriptionClient) Delete() *TranscriptionDelete {
	mutation := newTranscriptionMutation(c.config, OpDelete)
	return &TranscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TranscriptionClient) DeleteOne(t *Transcription) *TranscriptionDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TranscriptionClient) DeleteOneID(id int) *TranscriptionDeleteOne {
	builder := c.Delete().Where(transcription.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TranscriptionDeleteOne{builder}
}

// Query returns a query builder for Transcription.
func (c *TranscriptionClient) Query() *TranscriptionQuery {
	return &TranscriptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTranscription},
		inters: c.Interceptors(),
	}
}

// Get returns a Transcription entity by its id.
func (c *TranscriptionClient) Get(ctx context.Context, id int) (*Transcription, error) {
	return c.Query().Where(transcription.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TranscriptionClient) GetX(ctx context.Context, id int) *Transcription {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTranslations queries the translations edge of a Transcription.
func (c *TranscriptionClient) QueryTranslations(t *Transcription) *TranslationQuery {
	query := (&TranslationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(transcription.Table, transcription.FieldID, id),
			sqlgraph.To(translation.Table, translation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, transcription.TranslationsTable, transcription.TranslationsColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TranscriptionClient) Hooks() []Hook {
	return c.hooks.Transcription
}

// Interceptors returns the client interceptors.
func (c *TranscriptionClient) Interceptors() []Interceptor {
	return c.inters.Transcription
}

func (c *TranscriptionClient) mutate(ctx context.Context, m *TranscriptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TranscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TranscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TranscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TranscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Transcription mutation op: %q", m.Op())
	}
}

// TranslationClient is a client for the Translation schema.
type TranslationClient struct {
	config
}

// NewTranslationClient returns a client for the Translation from the given config.
func NewTranslationClient(c config) *TranslationClient {
	return &TranslationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `translation.Hooks(f(g(h())))`.
func (c *TranslationClient) Use(hooks ...Hook) {
	c.hooks.Translation = append(c.hooks.Translation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `translation.Intercept(f(g(h())))`.
func (c *TranslationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Translation = append(c.inters.Translation, interceptors...)
}

// Create returns a builder for creating a Translation entity.
func (c *TranslationClient) Create() *TranslationCreate {
	mutation := newTranslationMutation(c.config, OpCreate)
	return &TranslationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Translation entities.
func (c *TranslationClient) CreateBulk(builders ...*TranslationCreate) *TranslationCreateBulk {
	return &TranslationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TranslationClient) MapCreateBulk(slice any, setFunc func(*TranslationCreate, int)) *TranslationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TranslationCreateBulk{err: fmt.Errorf("calling to TranslationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TranslationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TranslationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Translation.
func (c *TranslationClient) Update() *TranslationUpdate {
	mutation := newTranslationMutation(c.config, OpUpdate)
	return &TranslationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TranslationClient) UpdateOne(t *Translation) *TranslationUpdateOne {
	mutation := newTranslationMutation(c.config, OpUpdateOne, withTranslation(t))
	return &TranslationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TranslationClient) UpdateOneID(id int) *TranslationUpdateOne {
	mutation := newTranslationMutation(c.config, OpUpdateOne, withTranslationID(id))
	return &TranslationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Translation.
func (c *TranslationClient) Delete() *TranslationDelete {
	mutation := newTranslationMutation(c.config, OpDelete)
	return &TranslationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TranslationClient) DeleteOne(t *Translation) *TranslationDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TranslationClient) DeleteOneID(id int) *TranslationDeleteOne {
	builder := c.Delete().Where(translation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TranslationDeleteOne{builder}
}

// Query returns a query builder for Translation.
func (c *TranslationClient) Query() *TranslationQuery {
	return &TranslationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTranslation},
		inters: c.Interceptors(),
	}
}

// Get returns a Translation entity by its id.
func (c *TranslationClient) Get(ctx context.Context, id int) (*Translation, error) {
	return c.Query().Where(translation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TranslationClient) GetX(ctx context.Context, id int) *Translation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TranslationClient) Hooks() []Hook {
	return c.hooks.Translation
}

// Interceptors returns the client interceptors.
func (c *TranslationClient) Interceptors() []Interceptor {
	return c.inters.Translation
}

func (c *TranslationClient) mutate(ctx context.Context, m *TranslationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TranslationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TranslationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TranslationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TranslationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Translation mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Transcription, Translation []ent.Hook
	}
	inters struct {
		Transcription, Translation []ent.Interceptor
	}
)
